apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: goapp 
  janus-idp.io/tekton: goapp
  backstage.io/kubernetes-id: goapp
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: goapp
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  