apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: goapp
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: goapp 
  name: goapp
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: goapp
    weight: 100 
